name: "Build Heister's Haptics Prerelease"
on: 
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      release_name:
        description: Specific codename for release
        required: true
        default: ""
jobs:
  build_multiple_os:
    name: Build ${{ matrix.artifact_name }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: i686-pc-windows-gnu
            artifact_name: haptics-gnu
            extras: unzip
        toolchain:
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install Extras
        if: ${{ matrix.extras }}
        run: sudo apt install ${{ matrix.extras }} -y

      - name: Get HapticsLib Release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: yupiel
          repo: hapticslib
          excludes: prerelease, draft
          
      - name: Unzip HapticsLib DLL
        run: unzip hapticslib-win.zip -d /tmp/dll
          
      - name: Copy DLL
        run: cp /tmp/dll/hapticslib.dll .

      - name: Clean Directory
        run: rm -r ./.git* *.zip
        
      - name: Zip Mod
        uses: vimtor/action-zip@v1.2
        with:
          files: ./**/*
          dest: ${{ matrix.artifact_name }}.zip

      - name: Create Pre-Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ~/haptics-artifacts/**/*.zip
          name: "Heister's Haptics Pre-Release v0.1.0-rc${{ github.run_number }} ${{ github.event.inputs.release_name }}"
          prerelease: true
          tag: "v0.1.0-rc${{ github.run_number }}"    
