name: "Build Heister's Haptics Prerelease"
on: 
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      release_name:
        description: Specific codename for release
        required: true
        default: ""
jobs:
  bundle:
    name: Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install Extras
        run: sudo apt install unzip -y

      - name: Get HapticsLib Release
        id: hapticslib
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: yupiel
          repo: hapticslib
          excludes: prerelease, draft

      - name: Fetch Latest Hapticslib Release
        run: curl https://github.com/yupiel/hapticslib/releases/latest/download/hapticslib-win.zip -o ./hapticslib-win.zip
      - run: ls -a
          
      - name: Unzip HapticsLib DLL
        run: unzip hapticslib-win.zip -d /tmp/dll
          
      - name: Copy DLL
        run: cp /tmp/dll/hapticslib.dll .

      - name: Clean Directory
        run: rm -r ./.git* *.zip
        
      - name: Zip Mod
        uses: vimtor/action-zip@v1.2
        with:
          files: ./**/*
          dest: "Heister's Haptics.zip"

      - name: Create Pre-Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./Heister's Haptics.zip"
          name: "Heister's Haptics Pre-Release v0.1.0-rc${{ github.run_number }} ${{ github.event.inputs.release_name }}"
          prerelease: true
          tag: "v0.1.0-rc${{ github.run_number }}"    
